const tasks=JSON.parse(localStorage.getItem('xcar_tasks')||localStorage.getItem('future_tasks')||'[]');
const conversations=JSON.parse(localStorage.getItem('xcar_conversations')||localStorage.getItem('future_conversations')||'[]');
let activeId=localStorage.getItem('xcar_active')||localStorage.getItem('future_active_conversation');
const notes=document.querySelector('#notes');notes.value=localStorage.getItem('xcar_notes')||localStorage.getItem('future_notes')||'';
const messages=document.querySelector('#chatMessages'),input=document.querySelector('#chatInput'),aiStatus=document.querySelector('#aiStatus');
const skills=[
{id:'code',icon:'💻',name:'Code',desc:'Développer, déboguer et expliquer.',level:94},
{id:'python',icon:'🐍',name:'Python',desc:'Scripts, logique, automatisation et data.',level:91},
{id:'javascript',icon:'⚡',name:'JavaScript',desc:'Web moderne, DOM et logique.',level:93},
{id:'html',icon:'🌐',name:'HTML/CSS',desc:'Interfaces responsive et accessibles.',level:95},
{id:'debug',icon:'🐞',name:'Debugger',desc:'Trouver et expliquer les bugs.',level:89},
{id:'architect',icon:'🏗️',name:'Architect',desc:'Structurer des projets solides.',level:87},
{id:'focus',icon:'🎯',name:'Focus',desc:'Prioriser et transformer les objectifs.',level:92},
{id:'creative',icon:'✨',name:'Creative',desc:'Idées, concepts et prototypes.',level:86},
{id:'learn',icon:'🧠',name:'Learn',desc:'Plans d’apprentissage progressifs.',level:90},
{id:'data',icon:'📊',name:'Analytics',desc:'Lire les tendances et synthétiser.',level:82},
{id:'security',icon:'🛡️',name:'Security',desc:'Bonnes pratiques et audit défensif.',level:80},
{id:'planner',icon:'⚙️',name:'Planner',desc:'Organiser missions et routines.',level:88}
];
const templates={
blank:{lang:'html',code:`<!doctype html>\n<html lang="fr">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Mon prototype</title></head>\n<body>\n  <h1>Bonjour X-Carl 🚀</h1>\n  <p>Commence à coder ici.</p>\n</body>\n</html>`},
landing:{lang:'html',code:`<!doctype html>\n<html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui;margin:0;min-height:100vh;display:grid;place-items:center;background:#0b1020;color:white}main{text-align:center;padding:48px}button{padding:12px 18px;border:0;border-radius:12px;cursor:pointer}</style></head>\n<body><main><h1>Nova Studio ✦</h1><p>Une landing page moderne générée dans X-Carl Dev Lab.</p><button onclick="alert('Ça marche !')">Tester</button></main></body></html>`},
dashboard:{lang:'html',code:`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui;background:#f4f6fb;margin:0;padding:30px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{background:white;padding:22px;border-radius:18px;box-shadow:0 8px 25px #0001}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><h1>Analytics Dashboard</h1><div class="grid"><div class="card"><b>1,248</b><p>Utilisateurs</p></div><div class="card"><b>86%</b><p>Progression</p></div><div class="card"><b>42</b><p>Missions</p></div></div></body></html>`},
game:{lang:'javascript',code:`const canvas=document.createElement('canvas');canvas.width=500;canvas.height=300;document.body.style.margin='0';document.body.style.background='#10162a';document.body.style.display='grid';document.body.style.placeItems='center';document.body.append(canvas);const ctx=canvas.getContext('2d');let x=50,y=50,dx=3,dy=2;function loop(){ctx.fillStyle='#10162a';ctx.fillRect(0,0,500,300);ctx.fillStyle='#8b7cff';ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fill();x+=dx;y+=dy;if(x<18||x>482)dx*=-1;if(y<18||y>282)dy*=-1;requestAnimationFrame(loop)}loop();`},
python:{lang:'python',code:`def analyser_missions(missions):\n    """Retourne les missions non terminées."""\n    return [m for m in missions if not m.get("done")]\n\nmissions = [\n    {"title": "Construire le prototype", "done": False},\n    {"title": "Tester l'interface", "done": True},\n]\nprint(analyser_missions(missions))`},
api:{lang:'javascript',code:`async function appelerAPI(url, options = {}) {\n  const response = await fetch(url, {\n    headers: { "Content-Type": "application/json" },\n    ...options\n  });\n  if (!response.ok) throw new Error("Erreur HTTP " + response.status);\n  return response.json();\n}\n\n// Utilise cette fonction dans ton propre backend.\nconsole.log("API helper prêt");`}
};
const skillsGrid=document.querySelector('#skillsGrid');
skillsGrid.innerHTML=skills.map(s=>`<button class="skill" data-skill="${s.name}"><div class="skill-top"><span class="skill-icon">${s.icon}</span><span class="counter">${s.level}%</span></div><div class="skill-name">${s.name}</div><div class="skill-desc">${s.desc}</div><div class="skill-bar"><span style="width:${s.level}%"></span></div></button>`).join('');
document.querySelector('#skillCount').textContent=skills.length;

function persist(){localStorage.setItem('xcar_tasks',JSON.stringify(tasks));localStorage.setItem('xcar_conversations',JSON.stringify(conversations));localStorage.setItem('xcar_active',activeId||'');localStorage.setItem('xcar_notes',notes.value)}
function getActive(){return conversations.find(c=>c.id===activeId)||null}
function createConversation(){const c={id:Date.now().toString(36),title:'Nouvelle mission',createdAt:new Date().toISOString(),messages:[]};conversations.unshift(c);activeId=c.id;persist();loadConversation()}
function addMessage(role,value,persistMsg=true){const el=document.createElement('div');el.className=`message ${role}`;el.textContent=value;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;if(persistMsg){const c=getActive();if(c){c.messages.push({role,value});if(c.messages.length===1)c.title=value.slice(0,40);persist();renderConversations()}}}
function loadConversation(){const c=getActive();if(!c)return createConversation();messages.innerHTML='';if(!c.messages.length)addMessage('assistant','Salut 👋 Je suis X-Carl. Mode développeur prêt : Python, HTML/CSS, JavaScript, debugging, architecture et prototypes. Donne-moi une mission.',false);else c.messages.forEach(m=>addMessage(m.role,m.value,false));renderConversations()}
function renderConversations(){const box=document.querySelector('#conversationList');box.innerHTML='';conversations.forEach(c=>{const b=document.createElement('button');b.className='conversation-item '+(c.id===activeId?'active':'');b.textContent=c.title;b.onclick=()=>{activeId=c.id;persist();loadConversation()};box.appendChild(b)})}
function saveTasks(){persist();renderTasks();drawChart()}
function addTask(value,priority='normal'){const clean=value.trim();if(!clean)return false;tasks.unshift({text:clean,priority,done:false,createdAt:Date.now()});saveTasks();return true}
function renderTasks(){const list=document.querySelector('#taskList');list.innerHTML='';tasks.forEach((t,i)=>{const li=document.createElement('li');li.className='task '+(t.done?'done':'');li.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><span class="task-text"></span><span class="priority">${t.priority}</span><button class="delete">×</button>`;li.querySelector('.task-text').textContent=t.text;li.querySelector('input').onchange=()=>{t.done=!t.done;saveTasks()};li.querySelector('.delete').onclick=()=>{tasks.splice(i,1);saveTasks()};list.appendChild(li)});const done=tasks.filter(t=>t.done).length,total=tasks.length,pct=total?Math.round(done/total*100):0;document.querySelector('#taskCount').textContent=total;document.querySelector('#progressBar').style.width=pct+'%';document.querySelector('#progressText').textContent=`${pct}% terminé • ${done}/${total}`;updateXP()}
function updateXP(){const done=tasks.filter(t=>t.done).length;const xp=done*25+Math.min(tasks.length*5,50);const level=Math.floor(xp/100)+1;document.querySelector('#level').textContent=level;document.querySelector('#xpText').textContent=`${xp%100} / 100`;document.querySelector('#xpBar').style.width=(xp%100)+'%';document.querySelector('#streak').textContent=done;}
function drawChart(){const data=tasks.length?[10,18,25,32,45,Math.min(80,45+tasks.length*5),Math.min(95,55+tasks.filter(t=>t.done).length*8)]:[18,35,27,48,40,64,52];document.querySelector('#chartBars').innerHTML=data.map(v=>`<span class="bar" style="height:${v}%"></span>`).join('')}
function localAssistant(q){const l=q.toLowerCase();if(/^(salut|bonjour|hello|bonsoir)/.test(l))return'Salut 👋 X-Carl est opérationnel. Choisis un skill ou donne-moi une mission.';if(l.includes('dev lab')||l.includes('éditeur de code')){document.querySelector('#devLab').scrollIntoView({behavior:'smooth'});return'🧪 Dev Lab ouvert. Choisis un langage et un modèle, puis prévisualise ton prototype.'}if(l.includes('montre')&&l.includes('tâche'))return tasks.length?tasks.map((t,i)=>`${i+1}. ${t.done?'✅':'⬜'} ${t.text} — ${t.priority}`).join('\n'):'Aucune mission pour le moment.';if(l.startsWith('ajoute une tâche')||l.startsWith('ajoute une tache')){const v=q.replace(/^ajoute une t[aâ]che\s*:? */i,'');return addTask(v)?`Mission ajoutée ⚡ ${v}`:'Écris par exemple : ajoute une tâche : finir mon prototype.'}if(l.startsWith('note ')||l.startsWith('note:')){const v=q.replace(/^note\s*:? */i,'');notes.value=notes.value?`${notes.value}\n${v}`:v;persist();return'Information enregistrée dans Memory Core 🧠.'}if(l.includes('combien')&&l.includes('tâche'))return`Tu as ${tasks.length} mission(s), dont ${tasks.filter(t=>!t.done).length} active(s).`;if(l.includes('mémoire')||l.includes('memoire'))return notes.value?`Memory Core :\n${notes.value}`:'Memory Core est vide.';return null}
async function askAI(q){const local=localAssistant(q);if(local){aiStatus.textContent='LOCAL';addMessage('assistant',local);return}aiStatus.textContent='AI…';try{const c=getActive();const history=(c?.messages||[]).slice(-12);const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,memory:notes.value,tasks,history,assistant:'X-Carl',skills:skills.map(s=>s.name)})});if(!r.ok)throw new Error('API');const d=await r.json();addMessage('assistant',d.reply||'Réponse vide.');aiStatus.textContent='AI ONLINE'}catch(e){aiStatus.textContent='LOCAL';addMessage('assistant','Le moteur IA distant n’est pas disponible. X-Carl garde ses fonctions locales actives.')}}

const editor=document.querySelector('#codeEditor'),langSelect=document.querySelector('#languageSelect'),templateSelect=document.querySelector('#templateSelect'),frame=document.querySelector('#previewFrame');
function setEditor(code,lang='html'){editor.value=code;langSelect.value=lang;document.querySelector('#codeMeta').textContent=lang.toUpperCase();document.querySelector('#previewStatus').textContent='READY'}
function runCode(){const lang=langSelect.value;const code=editor.value;document.querySelector('#previewStatus').textContent='RUNNING';if(lang==='python'||lang==='json'||lang==='sql'){frame.srcdoc=`<html><body style="font-family:system-ui;padding:20px;background:#0b1020;color:#eef2ff"><h3>Mode ${lang.toUpperCase()}</h3><p>Prévisualisation navigateur non-exécutée pour ce langage.</p><pre style="white-space:pre-wrap;background:#111a2c;padding:15px;border-radius:12px;overflow:auto"></pre></body></html>`;frame.onload=()=>{frame.contentDocument.querySelector('pre').textContent=code;document.querySelector('#previewStatus').textContent='SAFE PREVIEW'};return}let src=code;if(lang==='javascript')src=`<!doctype html><html><body><div id="app"></div><script>${code.replace(/<\/script/gi,'<\\/script')}<\/script></body></html>`;frame.srcdoc=src;setTimeout(()=>document.querySelector('#previewStatus').textContent='LIVE',250)}
function downloadCode(){const ext={html:'html',javascript:'js',python:'py',json:'json',sql:'sql'}[langSelect.value]||'txt';const blob=new Blob([editor.value],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`x-carl-project.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function copyCode(){try{await navigator.clipboard.writeText(editor.value);document.querySelector('#copyCode').textContent='✓ Copié';setTimeout(()=>document.querySelector('#copyCode').textContent='Copier',1200)}catch(e){alert('Copie non disponible dans ce navigateur.')}}
function exportData(){const data={version:2,exportedAt:new Date().toISOString(),tasks,conversations,notes:notes.value,code:editor.value,language:langSelect.value};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='x-carl-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(Array.isArray(d.tasks)){tasks.splice(0,tasks.length,...d.tasks)}if(Array.isArray(d.conversations)){conversations.splice(0,conversations.length,...d.conversations);activeId=conversations[0]?.id||activeId}if(typeof d.notes==='string')notes.value=d.notes;if(typeof d.code==='string')setEditor(d.code,d.language||'html');persist();renderTasks();loadConversation();alert('Backup X-Carl importé ✓')}catch(e){alert('Backup invalide.')}};reader.readAsText(file)}

document.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();const i=document.querySelector('#taskInput');if(addTask(i.value,document.querySelector('#priorityInput').value)){i.value='';i.focus()}};
document.querySelector('#saveNote').onclick=()=>{persist();alert('Memory Core sauvegardé 🧠')};
document.querySelector('#chatForm').onsubmit=e=>{e.preventDefault();const v=input.value.trim();if(!v)return;input.value='';addMessage('user',v);askAI(v)};
document.querySelector('#newConversation').onclick=createConversation;document.querySelector('#newConversationSide').onclick=createConversation;
document.querySelector('#focusBtn').onclick=()=>{document.body.classList.toggle('focus-mode');document.querySelector('#focusBtn').textContent=document.body.classList.contains('focus-mode')?'✕ Quitter Focus':'⚡ Mode Focus'};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;input.focus()});document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{const s=b.dataset.skill;input.value=`Active le skill ${s} et aide-moi à avancer.`;input.focus();document.querySelector('#chatForm').scrollIntoView({behavior:'smooth'})});
document.querySelector('#loadTemplate').onclick=()=>{const t=templates[templateSelect.value]||templates.blank;setEditor(t.code,t.lang);runCode()};langSelect.onchange=()=>{document.querySelector('#codeMeta').textContent=langSelect.value.toUpperCase()};document.querySelector('#runCode').onclick=runCode;document.querySelector('#copyCode').onclick=copyCode;document.querySelector('#downloadCode').onclick=downloadCode;
document.querySelector('#exportBtn').onclick=exportData;document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0])};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang='fr-FR';rec.interimResults=false;rec.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};document.querySelector('#voiceButton').onclick=()=>rec.start();document.querySelector('#voiceStatus').textContent='READY'}else{document.querySelector('#voiceButton').disabled=true;document.querySelector('#voiceStatus').textContent='UNAVAILABLE'}
if(!conversations.length)createConversation();else{if(!activeId||!getActive())activeId=conversations[0].id;loadConversation()}renderTasks();drawChart();setEditor(templates.landing.code,'html');runCode();